// <auto-generated />
using System;
using Maildesk.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maildesk.Api.Migrations
{
    [DbContext(typeof(MaildeskDbContext))]
    [Migration("20260503025021_InitialErdSchema")]
    partial class InitialErdSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maildesk.Api.Entities.SuratKeluar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("FileLampiran")
                        .HasColumnType("bytea")
                        .HasColumnName("file_lampiran");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Kepada")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("kepada");

                    b.Property<string>("NamaFile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nama_file");

                    b.Property<string>("NoSurat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("no_surat");

                    b.Property<string>("NomorAgenda")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nomor_agenda");

                    b.Property<int?>("PembuatId")
                        .HasColumnType("integer")
                        .HasColumnName("pembuat_id");

                    b.Property<string>("Perihal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("perihal");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TanggalSurat")
                        .HasColumnType("date")
                        .HasColumnName("tanggal_surat");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Kepada");

                    b.HasIndex("NoSurat");

                    b.HasIndex("NomorAgenda")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TanggalSurat");

                    b.HasIndex("TanggalSurat", "NomorAgenda");

                    b.ToTable("surat_keluar", (string)null);
                });

            modelBuilder.Entity("Maildesk.Api.Entities.SuratMasuk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AsalPengirim")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("asal_pengirim");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("FileLampiran")
                        .HasColumnType("bytea")
                        .HasColumnName("file_lampiran");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("NamaFile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nama_file");

                    b.Property<string>("NoSurat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("no_surat");

                    b.Property<string>("NomorAgenda")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nomor_agenda");

                    b.Property<string>("Perihal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("perihal");

                    b.Property<DateOnly>("TanggalSurat")
                        .HasColumnType("date")
                        .HasColumnName("tanggal_surat");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AsalPengirim");

                    b.HasIndex("IsArchived");

                    b.HasIndex("NomorAgenda")
                        .IsUnique();

                    b.HasIndex("TanggalSurat");

                    b.ToTable("surat_masuk", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
