// <auto-generated />
using System;
using Maildesk.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maildesk.Api.Migrations
{
    [DbContext(typeof(MaildeskDbContext))]
    [Migration("20260428130900_AddSuratKeluarSearch")]
    partial class AddSuratKeluarSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maildesk.Api.Entities.SuratKeluar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Deskripsi")
                        .HasColumnType("text")
                        .HasColumnName("deskripsi");

                    b.Property<string>("DibuatOleh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dibuat_oleh");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dibuat_pada");

                    b.Property<string>("InstansiPenerima")
                        .HasColumnType("text")
                        .HasColumnName("instansi_penerima");

                    b.Property<string>("JenisSumber")
                        .HasColumnType("text")
                        .HasColumnName("jenis_sumber");

                    b.Property<string>("KodeKlasifikasi")
                        .HasColumnType("text")
                        .HasColumnName("kode_klasifikasi");

                    b.Property<string>("NamaPenerima")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_penerima");

                    b.Property<string>("NomorAgenda")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomor_agenda");

                    b.Property<string>("NomorSurat")
                        .HasColumnType("text")
                        .HasColumnName("nomor_surat");

                    b.Property<string>("Perihal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("perihal");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateOnly>("TanggalKeluar")
                        .HasColumnType("date")
                        .HasColumnName("tanggal_keluar");

                    b.Property<DateOnly?>("TanggalSurat")
                        .HasColumnType("date")
                        .HasColumnName("tanggal_surat");

                    b.Property<string>("TingkatPrioritas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tingkat_prioritas");

                    b.HasKey("Id");

                    b.HasIndex("JenisSumber");

                    b.HasIndex("NomorAgenda");

                    b.HasIndex("NomorSurat");

                    b.HasIndex("Status");

                    b.HasIndex("TanggalKeluar");

                    b.HasIndex("TanggalKeluar", "NomorAgenda");

                    b.ToTable("surat_keluar", (string)null);
                });

            modelBuilder.Entity("Maildesk.Api.Entities.SuratMasuk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Deskripsi")
                        .HasColumnType("text")
                        .HasColumnName("deskripsi");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dibuat_pada");

                    b.Property<string>("InstansiPengirim")
                        .HasColumnType("text")
                        .HasColumnName("instansi_pengirim");

                    b.Property<string>("JenisSumber")
                        .HasColumnType("text")
                        .HasColumnName("jenis_sumber");

                    b.Property<string>("KodeKlasifikasi")
                        .HasColumnType("text")
                        .HasColumnName("kode_klasifikasi");

                    b.Property<string>("NamaPengirim")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama_pengirim");

                    b.Property<string>("NomorAgenda")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomor_agenda");

                    b.Property<string>("NomorSurat")
                        .HasColumnType("text")
                        .HasColumnName("nomor_surat");

                    b.Property<string>("Perihal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("perihal");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateOnly>("TanggalDiterima")
                        .HasColumnType("date")
                        .HasColumnName("tanggal_diterima");

                    b.Property<DateOnly?>("TanggalSurat")
                        .HasColumnType("date")
                        .HasColumnName("tanggal_surat");

                    b.Property<string>("TingkatPrioritas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tingkat_prioritas");

                    b.HasKey("Id");

                    b.HasIndex("JenisSumber");

                    b.HasIndex("NomorAgenda");

                    b.HasIndex("Status");

                    b.HasIndex("TanggalDiterima");

                    b.HasIndex("TanggalDiterima", "NomorAgenda");

                    b.ToTable("surat_masuk", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
